/**
 * IMOF Exam Portal — Design Tokens
 * Single source of truth for color, type, radii, shadows, motion.
 *
 * Usage (no new deps required):
 *   import { tokens, cssVariables, tailwindExtend } from './tokens.js'
 *
 * Tailwind wiring (when Tailwind is added later, do NOT edit this file's values):
 *   - Tailwind v3: spread `tailwindExtend` into tailwind.config.js `theme.extend`
 *   - Tailwind v4: map these vars in CSS with `@theme { --color-primary-900: ... }`
 *     or inject `:root { ... }` with the `cssVariables` string below.
 *
 * Scaffold note: existing `src/index.css` (`--text`, `--bg`, `--accent` purple)
 * is left untouched. Import these tokens alongside it; IMOF components should
 * reference tokens below, not the Vite defaults.
 */

export const colors = {
  brand: {
    // Primary — institutional trust, header/nav/footer, exam chrome
    primary: '#0B2F6B',
    primaryDeep: '#071E45', // footer bg, exam-player top bar
    primaryInk: '#061733', // text on light, high-contrast headings
    // Secondary — interactive blue, links, active states
    secondary: '#1450A0',
    secondaryHover: '#0F3E7E',
    secondarySoft: '#E3EDFB', // selected nav pill, info bg
    secondaryBorder: '#B9CFF0',
    // Accent — saffron, CTAs + energy. Use sparingly (1 per viewport).
    accent: '#F59E0B',
    accentHover: '#D97706',
    accentSoft: '#FEF3C7', // ticker bg, highlight wash
    accentInk: '#92400E', // text on accentSoft (passes AA)
  },

  // Full ramps for hover / focus / data-viz (all derived from the 3 anchors)
  primaryRamp: {
    50: '#EEF3FB',
    100: '#DCE7F6',
    200: '#B9CFF0',
    300: '#8AAEDE',
    400: '#4E82C4',
    500: '#245FAB',
    600: '#1450A0',
    700: '#0F3E7E',
    800: '#0B2F6B',
    900: '#071E45',
    950: '#061733',
  },
  accentRamp: {
    50: '#FFFBEB',
    100: '#FEF3C7',
    200: '#FDE68A',
    300: '#FCD34D',
    400: '#FBBF24',
    500: '#F59E0B',
    600: '#D97706',
    700: '#B45309',
    800: '#92400E',
    900: '#78350F',
  },

  neutral: {
    white: '#FFFFFF',
    paper: '#F8FAFC', // page bg
    muted: '#F1F5F9', // card wash, table zebra
    border: '#E2E8F0',
    borderStrong: '#CBD5E1',
    text: '#0F172A', // slate-900
    textMuted: '#475569', // slate-600 — secondary copy
    textFaint: '#64748B', // slate-500 — captions only (never body)
    onDark: '#FFFFFF',
    onDarkMuted: '#CBD5E1',
  },

  semantic: {
    success: '#16A34A',
    successHover: '#15803D',
    successSoft: '#DCFCE7',
    successBorder: '#86EFAC',
    successInk: '#14532D',
    error: '#DC2626',
    errorHover: '#B91C1C',
    errorSoft: '#FEE2E2',
    errorBorder: '#FCA5A5',
    errorInk: '#7F1D1D',
    warning: '#B45309', // amber-700 as text (AA on white); bg uses accentSoft
    warningSoft: '#FEF3C7',
    warningBorder: '#FCD34D',
    info: '#0284C7',
    infoSoft: '#E0F2FE',
    infoBorder: '#7DD3FC',
    infoInk: '#0C4A6E',
  },

  // Exam-player palette states (must never rely on color alone — see UI-SPEC)
  exam: {
    unvisited: '#E2E8F0',
    unanswered: '#EF4444', // red dot/ring
    answered: '#16A34A', // green fill
    marked: '#8B5CF6', // violet for "mark for review"
    current: '#0B2F6B', // navy ring + offset
  },
};

export const fonts = {
  // IMOF graft (imofedu.com): display/menus/labels use Righteous (headings #050748);
  // body stays Inter for exam readability (site body Righteous is display-only here).
  // Bubblegum Sans reserved for tiny accent eyebrows — never body copy.
  display: '"Righteous", "Plus Jakarta Sans", "Noto Sans Tamil", "Noto Sans", system-ui, sans-serif',
  imof: '"Righteous", "Plus Jakarta Sans", system-ui, sans-serif',
  bubble: '"Bubblegum Sans", "Righteous", cursive',
  body: '"Inter", "Noto Sans Tamil", "Noto Sans", system-ui, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, SFMono-Regular, Consolas, monospace', // user_id, timer, scores
  googleFontsHref:
    'https://fonts.googleapis.com/css2?family=Righteous&family=Bubblegum+Sans&family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap',

  // Direct ports from imofedu.com style.css
  imofSite: {
    heading: '#050748', // h1-h6 color
    body: '#6a6a8e', // site body copy
    menuUnderline: '#EF7F1B', // .sbmenu>a:after 5px bar
    heroBtn: '#FF3D00', // .slide-content .btn bg
    footerHover: '#00BCD4', // .footer-links a:hover
    ease: 'cubic-bezier(0.17, 0.85, 0.438, 0.99)', // global a/button easing
    menuSize: '15px',
    menuWeight: 500,
    menuTransform: 'uppercase',
  },

  scale: {
    display: { size: 'clamp(2rem, 5vw, 3.5rem)', lineHeight: 1.05, weight: 800, letterSpacing: '-0.02em' },
    h1: { size: 'clamp(1.75rem, 3.5vw, 2.5rem)', lineHeight: 1.15, weight: 800, letterSpacing: '-0.015em' },
    h2: { size: 'clamp(1.375rem, 2.5vw, 1.875rem)', lineHeight: 1.2, weight: 700, letterSpacing: '-0.01em' },
    h3: { size: '1.25rem', lineHeight: 1.3, weight: 700, letterSpacing: '0' },
    lead: { size: '1.125rem', lineHeight: 1.6, weight: 400, letterSpacing: '0' },
    body: { size: '1rem', lineHeight: 1.6, weight: 400, letterSpacing: '0' },
    small: { size: '0.875rem', lineHeight: 1.5, weight: 400, letterSpacing: '0' },
    caption: { size: '0.75rem', lineHeight: 1.45, weight: 500, letterSpacing: '0.04em' },
    eyebrow: {
      size: '0.75rem',
      lineHeight: 1.4,
      weight: 700,
      letterSpacing: '0.12em',
      transform: 'uppercase',
    },
  },
};

export const radii = {
  xs: '4px',
  sm: '8px',
  md: '12px',
  lg: '16px',
  xl: '24px',
  pill: '999px',
};

export const shadows = {
  none: 'none',
  sm: '0 1px 2px rgba(7, 30, 69, 0.08)',
  md: '0 4px 12px rgba(7, 30, 69, 0.10), 0 1px 3px rgba(7, 30, 69, 0.08)',
  lg: '0 12px 32px rgba(7, 30, 69, 0.16), 0 2px 8px rgba(7, 30, 69, 0.10)',
  navyGlow: '0 0 0 4px rgba(20, 80, 160, 0.18)',
  accentGlow: '0 8px 24px rgba(245, 158, 11, 0.35)',
};

export const spacing = {
  container: '1126px', // matches scaffold #root width — keeps migration smooth
  containerNarrow: '880px', // login / result
  examReader: '760px', // question card measure for readability
  sectionY: 'clamp(3rem, 7vw, 5.5rem)',
  cardPad: '1.5rem',
};

export const breakpoints = {
  sm: '640px',
  md: '768px',
  lg: '1024px', // scaffold breakpoint — nav collapses below this
  xl: '1280px',
};

export const motion = {
  durationFast: '120ms',
  durationBase: '200ms',
  durationSlow: '320ms',
  ease: 'cubic-bezier(0.22, 1, 0.36, 1)',
};

export const zIndex = {
  header: 40,
  ticker: 30,
  stickyExamBar: 30,
  dropdown: 50,
  modal: 100,
  toast: 110,
};

/** Flat CSS-variable map — inject once at app root when ready. */
export const cssVariables = `
:root {
  --imof-primary: ${colors.brand.primary};
  --imof-primary-deep: ${colors.brand.primaryDeep};
  --imof-primary-ink: ${colors.brand.primaryInk};
  --imof-secondary: ${colors.brand.secondary};
  --imof-secondary-hover: ${colors.brand.secondaryHover};
  --imof-secondary-soft: ${colors.brand.secondarySoft};
  --imof-accent: ${colors.brand.accent};
  --imof-accent-hover: ${colors.brand.accentHover};
  --imof-accent-soft: ${colors.brand.accentSoft};
  --imof-accent-ink: ${colors.brand.accentInk};
  --imof-bg: ${colors.neutral.paper};
  --imof-surface: ${colors.neutral.white};
  --imof-border: ${colors.neutral.border};
  --imof-text: ${colors.neutral.text};
  --imof-text-muted: ${colors.neutral.textMuted};
  --imof-success: ${colors.semantic.success};
  --imof-success-soft: ${colors.semantic.successSoft};
  --imof-error: ${colors.semantic.error};
  --imof-error-soft: ${colors.semantic.errorSoft};
  --imof-radius-md: ${radii.md};
  --imof-radius-lg: ${radii.lg};
  --imof-shadow-md: ${shadows.md};
  --imof-font-display: ${fonts.display};
  --imof-font-body: ${fonts.body};
}
`.trim();

/** Tailwind v3 `theme.extend` passthrough (add Tailwind later; no install here). */
export const tailwindExtend = {
  colors: {
    primary: colors.primaryRamp,
    accent: colors.accentRamp,
    ink: colors.brand.primaryInk,
    navy: colors.brand.primary,
    royal: colors.brand.secondary,
    saffron: colors.brand.accent,
    success: colors.semantic.success,
    danger: colors.semantic.error,
  },
  fontFamily: {
    display: [fonts.display],
    sans: [fonts.body],
    mono: [fonts.mono],
  },
  borderRadius: radii,
  boxShadow: shadows,
};

export const tokens = {
  colors,
  fonts,
  radii,
  shadows,
  spacing,
  breakpoints,
  motion,
  zIndex,
  cssVariables,
  tailwindExtend,
};

export default tokens;
